### ISSUE TITLE
Suggestion regarding action denylisting

### ISSUE THREAD

**Issue by Frichetten** [AbstractClass/CloudPrivs#1]
Hey there :wave: ! This project looks great. I really appreciate you building a tool for this problem space as some of the current tools available are a bit outdated. 

I noticed that you have a comment here 

> Note: some AWS functions can incur costs when called, I have deny-listed all operations starting with open or purchase to mitigate accidental costs, which appears to be safe in my own testing, but please use this with caution. I don't guarantee you won't accidentally incur costs when calling all these functions (even if it's without arguments)

I'd like to suggest changing the way you block actions from being called. A while back, when I was fuzzing the AWS API, I made the mistake of calling [shield:CreateSubscription](https://docs.aws.amazon.com/waf/latest/DDOSAPIReference/API_CreateSubscription.html). This subscribed my AWS account for [Shield Advanced](https://maturitymodel.security.aws.dev/en/3.-efficient/shield-advanced/) which is [$3,000](https://aws.amazon.com/shield/pricing/) per month (thankfully some kind folks inside AWS were able to resolve this without me paying). 

Rather than just denying actions which start with `open` or `purchase`, it might be a good idea to allowlist actions that start with `Get`, `List`, or `Describe` (sort of similar to how [enumerate-iam](https://github.com/andresriancho/enumerate-iam) does it). This would reduce the number of actions you can check for, but would mitigate a lot of the risk in the event that AWS creates a new service/action that costs money by default (and doesn't fall into the `open` or `purchase` category). 

Just a suggestion! Thank you again for working on this problem.

**Comment by AbstractClass** [comment]
Great suggestion actually, this was something I had been toying with the idea of, but I hadn't implemented it because I thought there was a chance with only "Get,List,Describe" I might miss valid test cases and in my own testing I say my account wasn't being charged. But you have shown that I still have gaps and might cost people money. I will push a new version shortly that only does `Get`, `List`, and `Describe`. I may introduce a flag or a config file in the future that will allow an override of this in case people want to risk it.

Solved in 0910e9e52d89516d6078d7ae55f6a01ff788a5b5 , thanks again for the feedback!
